# Generated by Django 5.0.4 on 2024-05-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcdHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hl_uid', models.IntegerField(unique=True)),
                ('date_open', models.DateTimeField()),
                ('built_year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AcdInstitute',
            fields=[
                ('inst_code', models.IntegerField(primary_key=True, serialize=False)),
                ('inst_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthEncrypt',
            fields=[
                ('username', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.BinaryField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AcdInsurance',
            fields=[
                ('ins_acct_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ins_company', models.CharField(max_length=30)),
                ('ins_street', models.CharField(max_length=30)),
                ('ins_city', models.CharField(max_length=30)),
                ('ins_state', models.CharField(max_length=2)),
                ('ins_zipcode', models.CharField(max_length=5)),
                ('yearly_prm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hl_uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acdbanking.acdhome')),
            ],
        ),
        migrations.CreateModel(
            name='AcdSafeAcnt',
            fields=[
                ('a_uid', models.BigIntegerField()),
                ('acct_type', models.CharField(max_length=2)),
                ('acct_name', models.CharField(max_length=30)),
                ('a_street', models.CharField(max_length=30)),
                ('a_city', models.CharField(max_length=30)),
                ('a_state', models.CharField(max_length=2)),
                ('a_zipcode', models.CharField(max_length=5)),
                ('surrogate_key', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'unique_together': {('a_uid', 'acct_type')},
            },
        ),
        migrations.CreateModel(
            name='AcdPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_uid', models.IntegerField(unique=True)),
                ('date_open', models.DateTimeField()),
                ('a_safe_acnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personal_Loan', to='acdbanking.acdsafeacnt', verbose_name='SAFE Unique Account')),
            ],
        ),
        migrations.AddField(
            model_name='acdhome',
            name='a_safe_acnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home_Loan', to='acdbanking.acdsafeacnt', verbose_name='SAFE Unique Account'),
        ),
        migrations.CreateModel(
            name='AcdCustomer',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_fname', models.CharField(max_length=30)),
                ('c_lname', models.CharField(max_length=30)),
                ('c_street', models.CharField(max_length=30)),
                ('c_city', models.CharField(max_length=30)),
                ('c_state', models.CharField(max_length=2)),
                ('c_zipcode', models.CharField(max_length=5)),
                ('a_safe_acnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Info', to='acdbanking.acdsafeacnt', verbose_name='SAFE Unique Account')),
            ],
        ),
        migrations.CreateModel(
            name='AcdChecking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_no', models.BigIntegerField(unique=True)),
                ('date_open', models.DateTimeField()),
                ('serv_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('a_safe_acnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Checking_Accounts', to='acdbanking.acdsafeacnt', verbose_name='SAFE Unique Account')),
            ],
        ),
        migrations.CreateModel(
            name='AcdSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_no', models.BigIntegerField(unique=True)),
                ('date_open', models.DateTimeField()),
                ('intrst_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('a_safe_acnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Savings_Accounts', to='acdbanking.acdsafeacnt', verbose_name='SAFE Unique Account')),
            ],
        ),
        migrations.CreateModel(
            name='AcdStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_uid', models.FloatField(unique=True)),
                ('date_open', models.DateTimeField()),
                ('student_id', models.CharField(max_length=6)),
                ('degree_type', models.CharField(max_length=13)),
                ('grad_month', models.CharField(max_length=10)),
                ('grad_year', models.SmallIntegerField()),
                ('a_safe_acnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Loan', to='acdbanking.acdsafeacnt', verbose_name='SAFE Unique Account')),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acdbanking.acdinstitute')),
            ],
        ),
        migrations.CreateModel(
            name='AcdLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_no', models.BigIntegerField()),
                ('loan_type', models.CharField(max_length=2)),
                ('loan_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('loan_months', models.SmallIntegerField()),
                ('loan_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('a_safe_acnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_Accounts', to='acdbanking.acdsafeacnt', verbose_name='SAFE Unique Account')),
            ],
            options={
                'unique_together': {('acct_no', 'loan_type')},
            },
        ),
    ]
